config/routes.rb
Rails.application.routes.draw do
  

 
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index' 
  resources :services
  resources :car_models
  resources :cars
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :service_transactions do
    resources :comments
    resources :service_todos, only: [:index, :new, :create] do
      member do
          patch :completed
          patch :on_going
          patch :paid
      end
    end
  end
 resources :service_transactions do 
    member do
      patch :finished
    end
  end
 resources :service_todos, only: [:show, :edit, :update, :destroy]
   resources :service_transactions 

  get 'home/index'

  root 'home#index'

end

app/models/service_todo.rb
class ServiceTodo < ActiveRecord::Base
  
  belongs_to :service_transaction
  belongs_to :service
  belongs_to :technician_in_charge, :class_name => 'User'
 
  


  scope :unpaid, -> {where(paid_at: nil)}
  scope :paid, -> {where.not(paid_at: nil)}
  validates :service_id, presence: true
  validates :technician_in_charge, presence: true
  
  def ongoing?
    !started_at.blank?
  end

  def completed?
  	!completed_at.blank? && !started_at.blank?
  end

  # def paid?
  # 	!paid_at.blank?
  # end

  
end

app/controllers/service_todos_controller.rb
class ServiceTodosController < ApplicationController
  before_action :set_service_transaction#, only: [:on_going, :completed]
  before_action :set_service_todo , except: [:create]
  # GET /service_todos
  # GET /service_todos.json
  
  # GET /service_todos/new
  def new
    @service_todo = ServiceTodo.new
  end

  # GET /service_todos/1/edit
  # def edit
  # end

  # POST /service_todos
  # POST /service_todos.json
  def create
   
    @service_todo = ServiceTodo.new(service_todo_params)
    @service_todo = ServiceTodo.create(params[:service_todo].permit(:service_id, :technician_in_charge_id))
    @service_todo.service_transaction_id = @service_transaction.id

    if current_user.role.name == "staff" || current_user.role.name == "admin"
      if @service_todo.save
        ServiceTodoMailer.new_service_todo_to_staff(@service_todo).deliver_later
        ServiceTodoMailer.new_service_todo_to_user(@service_todo).deliver_later
        ServiceTodoMailer.new_service_todo_to_technician(@service_todo).deliver_later
        Notification.create(user_id: @service_transaction.car.user_id,
                            notified_by_id: current_user.id,
                            car_id: @service_transaction.car_id,
                            service_transaction_id: @service_transaction.id,
                            notice_type: 'created a new task')
         Notification.create(user_id: @service_transaction.staff_in_charge_id,
                            notified_by_id: current_user.id,
                            car_id: @service_transaction.car_id,
                            service_transaction_id: @service_transaction.id,
                            notice_type: 'created a new task')
          Notification.create(user_id: @service_transaction.technician_in_charge_id,
                            notified_by_id: current_user.id,
                            car_id: @service_transaction.car_id,
                            service_transaction_id: @service_transaction.id,
                            notice_type: 'created a new task')
            if @service_todo.technician_in_charge_id == @service_transaction.technician_in_charge_id

            else
            Notification.create(user_id: @service_todo.technician_in_charge_id,
                            notified_by_id: current_user.id,
                            car_id: @service_transaction.car_id,
                            service_transaction_id: @service_transaction.id,
                            notice_type: 'created a new task')
            end
        redirect_to service_transaction_path(@service_transaction), notice: "Service Completed"
        # format.html { redirect_to @service_todo, notice: 'Service todo was successfully created.' }
        # format.json { render :show, status: :created, location: @service_todo }
      else
         
          respond_to do |format|
            format.html { redirect_to service_transaction_path(@service_transaction), notice: "Service Todo Error. Service cant be blank, and Technician in charge cant be blank" }
          end
      end
    else
      redirect_to service_transaction_path(@service_transaction), notice: "Only Admin and Staff Can Add Transaction"
    end

    
  end

  # PATCH/PUT /service_todos/1
  # PATCH/PUT /service_todos/1.json
  # def update
  #   respond_to do |format|
  #     if @service_todo.update(service_todo_params)
  #       format.html { redirect_to @service_todo, notice: 'Service todo was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @service_todo }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @service_todo.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # DELETE /service_todos/1
  # DELETE /service_todos/1.json
  def destroy
   
    @service_todo.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: 'Service todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


 def completed

    #ServiceTodoMailer.completed(@service_todo).deliver
    if current_user.role.name == "user" || current_user.role.name == "staff"
      redirect_to service_transaction_path(@service_transaction), notice: "Action Denied. Only Technicians and Admins have permission to mark this as on-going."
    else
      #block to check if it is on-going first
      if @service_todo.started_at.blank?
        redirect_to service_transaction_path(@service_transaction), notice: "Please Mark It as On-Going first"
        #end of check block
        #block to check users and staffs from the action
      elsif current_user.role.name == "user" || current_user.role.name == "staff"
        redirect_to service_transaction_path(@service_transaction), notice: "Action Denied.  Only Technicians and Admins have permission to mark this as complete."
      else
        #check if it the user is the admin or the technician in charge
        if current_user.id == @service_todo.technician_in_charge_id || current_user.role.name == "admin"
          @service_todo.update_attribute(:completed_at, Time.now)
           ServiceTodoMailer.completed(@service_todo).deliver_later
           Notification.create(user_id: @service_transaction.car.user_id,
                            notified_by_id: current_user.id,
                            car_id: @service_transaction.car_id,
                            service_transaction_id: @service_transaction.id,
                            notice_type: 'completed a task in your transaction.')
            Notification.create(user_id: @service_transaction.staff_in_charge_id,
                            notified_by_id: current_user.id,
                            car_id: @service_transaction.car_id,
                            service_transaction_id: @service_transaction.id,
                            notice_type: 'completed a task in your transaction.')
          redirect_to @service_transaction, notice: "Service Completed"
        else
          redirect_to @service_transaction, notice: "Action Denied. Only the Technician-In-Charge and Admins have permission to mark this as complete."
        end
      end
    end
  end   

  def on_going
    
    if current_user.role.name == "user" || current_user.role.name == "staff"
      redirect_to service_transaction_path(@service_transaction), notice: "Action Denied. Only Technicians and Admins have permission to mark this as on-going."


    else
      
      if current_user.id == @service_todo.technician_in_charge_id || current_user.role.name == "admin"
        @service_todo.update_attribute(:started_at, Time.now)
            ServiceTodoMailer.on_going(@service_todo).deliver_later
            Notification.create(user_id: @service_transaction.car.user_id,
                            notified_by_id: current_user.id,
                            car_id: @service_transaction.car_id,
                            service_transaction_id: @service_transaction.id,
                            notice_type: 'marked a task in your transaction as on-going.')
            Notification.create(user_id: @service_transaction.staff_in_charge_id,
                            notified_by_id: current_user.id,
                            car_id: @service_transaction.car_id,
                            service_transaction_id: @service_transaction.id,
                            notice_type: 'marked a task in your transaction as on-going.')
        redirect_to @service_transaction, notice: "Service On-going"
      else
         redirect_to @service_transaction, notice: "Action Denied. Only the Technician-In-Charge and Admins have permission to mark this as on-going."
      end
    end
  end   

  def paid
    #ServiceTodoMailer.paid(@service_todo).deliver
    @service_todo.update_attribute(:paid_at, Time.now)
    redirect_to @service_transaction, notice: "Service Paid, Please Update the Bill Balance"
  end   

 

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_service_transaction
    @service_transaction = ServiceTransaction.find(params[:service_transaction_id])
  end
    def set_service_todo
      @service_todo = ServiceTodo.find(params[:id])
    end

    # # Never trust parameters from the scary internet, only allow the white list through.
    def service_todo_params
      params.require(:service_todo).permit(:paid_at, :completed_at, :started_at, :service_transaction_id, :service_id, :technician_in_charge_id)
    end
end

app/helpers/service_todos_helper.rb
module ServiceTodosHelper
end

app/views/service_todos/_form.html.erb
<%= simple_form_for([@service_transaction, @service_transaction.service_todos.build]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  <!--   <%= f.input :paid_at %>
    <%= f.input :completed_at %>
    <%= f.input :started_at %> -->
    <%= f.association :service, :label_method => :name, :value_method => :id %>
  <%= f.association :technician_in_charge, collection: User.technician, :label_method => :email, :value_method => :id%>
  
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/service_todos/_service_todo.html.erb
<div class="panel panel-default ">
  	<% if service_todo.completed? %>  
  	<div class="panel-body completed_todo">
	<% elsif service_todo.ongoing? %>
	<div class="panel-body on_going_todo">
	<% else %>
	<div class="panel-body default_todo">
	<% end %>


  		<!-- for status of the service_todo -->
  		<div class="status_code">
		  	<% if service_todo.completed? %>
		
				 <b>Status: </b><span class="label label-success">Completed</span>

			<% elsif service_todo.ongoing? %>
				 <b>Status: </b><span class="label label-primary">On-Going</span>
			<% else %>
				<b>Status:</b> <span class="label label-default">On Queue</span>
			<% end %>
			</div>
    <b>Service:</b> <%= service_todo.service.name %><br>
    <b>Price:</b> <%= service_todo.service.price  %><br>
        <b>Mechanic: </b> <%= service_todo.technician_in_charge.try(:email)  %><br>
    <!-- conditions for roles -->
    <% if current_user.role.name == "user" %>

    <% else %>
	<!-- conditions for ongoing -->
	<p>
	<% if service_todo.ongoing? %>
			<%= link_to "Marked as On-Going", on_going_service_transaction_service_todo_path(@service_transaction, service_todo.id), method: :patch, data: {confirm: "Are you Sure you want to mark service as ON-GOING?"},class: "btn btn-primary disabled" %>
		<% else %>
			<%= link_to "Mark as On-Going", on_going_service_transaction_service_todo_path(@service_transaction, service_todo.id), method: :patch, data: {confirm: "Are you Sure you want to mark service as ON-GOING?"},class: "btn btn-primary" %>	
		<% end %>
		</p>
		<!-- end for conditions on-going-->

		<!-- conditions for being completed -->
	<p>	
	<% if service_todo.completed? %>
				<%= link_to "Marked as Complete", completed_service_transaction_service_todo_path(@service_transaction, service_todo.id), method: :patch, data: {confirm: "Are you sure you want to mark service as COMPLETED?"}, class: "btn btn-success disabled" %>
		<% else %>
			<%= link_to "Mark as Complete", completed_service_transaction_service_todo_path(@service_transaction, service_todo.id), method: :patch, data: {confirm: "Are you sure you want to mark service as COMPLETED?"}, class: "btn btn-success" %>
		<% end %>
	</p>
		<!-- end for completed conditions -->
		<% end %>
		<!-- end for conditional statements on roles -->
  </div>
</div>

app/views/service_todos/edit.html.erb
<h1>Editing Service Todo</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_todo %> |
<%= link_to 'Back', service_todos_path %>

app/views/service_todos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Service Todos</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Paid at</th>
      <th>Completed at</th>
      <th>Started at</th>
      <th>Service transaction</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_todos.each do |service_todo| %>
      <tr>
        <td><%= service_todo.paid_at %></td>
        <td><%= service_todo.completed_at %></td>
        <td><%= service_todo.started_at %></td>
        <td><%= service_todo.service_transaction.try(:id) %></td>
        <td><%= link_to 'Show', service_todo %></td>
        <td><%= link_to 'Edit', edit_service_todo_path(service_todo) %></td>
        <td><%= link_to 'Destroy', service_todo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service todo', new_service_todo_path %>

app/views/service_todos/new.html.erb
<h1>New Service Todo</h1>

<%= render 'form' %>

<%= link_to 'Back', service_todos_path %>

app/views/service_todos/show.html.erb
<p id="notice"><%= notice %></p>

<!-- <p>
  <strong>Paid at:</strong>
  <%= @service_todo.paid_at %>
</p>

<p>
  <strong>Completed at:</strong>
  <%= @service_todo.completed_at %>
</p>

<p>
  <strong>Started at:</strong>
  <%= @service_todo.started_at %>
</p> -->
<p>
  <strong>Service todo:</strong>
  <%= @service_todo.service.try(:name) %>
</p>

<p>
  <strong>Service transaction:</strong>
  <%= @service_todo.service_transaction.try(:id) %>
</p>

<%= link_to 'Edit', edit_service_todo_path(@service_todo) %> |
<%= link_to 'Back', service_todos_path %>