config/routes.rb
Rails.application.routes.draw do
  

 
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index' 
  resources :services
  resources :car_models
  resources :cars
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :service_transactions do
    resources :comments
    resources :service_todos, only: [:index, :new, :create] do
      member do
          patch :completed
          patch :on_going
          patch :paid
      end
    end
  end
 resources :service_transactions do 
    member do
      patch :finished
    end
  end
 resources :service_todos, only: [:show, :edit, :update, :destroy]
   resources :service_transactions 

  get 'home/index'

  root 'home#index'

end

app/models/car.rb
class Car < ActiveRecord::Base
  
  belongs_to :user
  belongs_to :car_manufacturer
  belongs_to :car_model
  has_many :service_transactions

  has_attached_file :picture, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :picture, content_type: /\Aimage\/.*\Z/
  validates :plate_number , presence: true, uniqueness: true
  validates :car_model_id, presence: true
  validates :user_id, presence: true
  validates :year, numericality: true, presence: true
  validates :plate_number, format: { with: /[A-Z]{2,3}-[0-9]{3,4}/,
    message: "Follow (XXX-999/XXX-9999/XX-9999)" }
  validates :picture, attachment_presence: true


  def self.search(search)
    if search
      where(["plate_number LIKE ?" , "%#{search}%"])
    else
      all
    end    
  end
end

app/models/car_manufacturer.rb
class CarManufacturer < ActiveRecord::Base

	has_many :cars, through: :car_models
	has_many :car_models

	validates :name, presence: true, uniqueness: true
	
end

app/models/car_model.rb
class CarModel < ActiveRecord::Base
  

  belongs_to :car_manufacturer
  has_many :cars
  #belongs_to :cars through: :car_manufacturer

  validates :name, presence: true, uniqueness: true
  validates :car_manufacturer_id, presence: true


end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :service_transaction

  validates :content, presence: true
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  

  
  belongs_to :user
  belongs_to :notified_by, :class_name => 'User'
  belongs_to :car
  belongs_to :service_transaction
  
  scope :unread, -> {where(read: false)}
end

app/models/role.rb
class Role < ActiveRecord::Base

	has_many :users

	validates :name, uniqueness: true, presence: true
end

app/models/service.rb
class Service < ActiveRecord::Base
	has_many :service_todos

	validates :name, uniqueness: true
	validates :price, presence: true
	validates :name, presence: true
    def self.search(search)
	    if search
	      where(["name LIKE ?" , "%#{search}%"])
	    else
	      all
	    end    
  	end
end

app/models/service_todo.rb
class ServiceTodo < ActiveRecord::Base
  
  belongs_to :service_transaction
  belongs_to :service
  belongs_to :technician_in_charge, :class_name => 'User'
 
  


  scope :unpaid, -> {where(paid_at: nil)}
  scope :paid, -> {where.not(paid_at: nil)}
  validates :service_id, presence: true
  validates :technician_in_charge, presence: true
  
  def ongoing?
    !started_at.blank?
  end

  def completed?
  	!completed_at.blank? && !started_at.blank?
  end

  # def paid?
  # 	!paid_at.blank?
  # end

  
end

app/models/service_transaction.rb
class ServiceTransaction < ActiveRecord::Base
  belongs_to :car

  has_many :service_todos
  has_many :comments
  has_many :notifications, dependent: :destroy
  accepts_nested_attributes_for :service_todos
  belongs_to :staff_in_charge, :class_name => 'User'
  belongs_to :technician_in_charge, :class_name => 'User'
  belongs_to :user

  validates :staff_in_charge_id , presence: true
  validates :technician_in_charge_id , presence: true
  validates :car_id 			, presence: true

  def finished?
  	!finished_at.blank?
  end

  def self.search(search)
    if search
      where(["id = ?" , "%#{search}%"])
    else
      all
    end    
  end
end

app/models/user.rb
class User < ActiveRecord::Base	
  



  belongs_to :role
  has_many :service_todos, :foreign_key => :technician_in_charge_id
  has_many :cars,  dependent: :destroy
  has_many :service_transactions, through: :cars
  has_many :comments,  dependent: :destroy
  after_initialize :set_default_role, :if => :new_record?
  has_many :notifications, dependent: :destroy
  validates :email, uniqueness: true
  validates :contact_number_prefix, numericality: true, presence: true
  validates :contact_number, numericality: true, presence: true, length: { is: 7}
  validates :first_name, length: { in: 2..20}
  validates :last_name, length: { in: 2..20}

  scope :admin, -> {where(role_id: 4)}
  scope :technician, -> {where(role_id: 3)}
  scope :staff, -> {where(role_id: 2)}
  scope :user, -> {where(role_id: 1)}

  def set_default_role
  	self.role_id = 1
  end
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable


end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  
  # GET /cars
  # GET /cars.json
  def index
    if user_signed_in?
       if current_user.role.name == "user"
      @cars = current_user.cars.where(["plate_number LIKE ?", "%#{params[:search]}%"]).paginate(:page => params[:page], :per_page => 10)
      else
        @cars = Car.search(params[:search]).paginate(:page => params[:page], :per_page => 10)
      end
    else
      redirect_to new_user_session_path
    end
   
  end

  # GET /cars/1
  # GET /cars/1.json
  def show

  	# u = User.where(:id => @car.edited_by)
    @service_transactions = ServiceTransaction.where(car_id: @car)
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
    if current_user.role.name == "technician"
      redirect_to root_path, notice: "Action Denied. You do not have permission to edit this"
    end
  end

  # POST /cars
  # POST /cars.json
  def create
    if current_user.role.name == "user"
      redirect_to root_path
      #@car = current_user.cars.build(car_params)
    elsif current_user.role.name == "admin" || current_user.role.name == "staff"
      @car = Car.new(car_params)
    else
       redirect_to root_path
    end 
    #@car.edited_by = current_user.id
    respond_to do |format|
      if @car.save
      	
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
  	 if current_user.role.name == "technician"
      redirect_to root_path, notice: "Action Denied. You do not have permission to edit this"
    end
  	#@car.edited_by = current_user.id
    respond_to do |format|
      if @car.update(car_params)
      	
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.



    def set_car
      @car = Car.find(params[:id])
    end


     

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:plate_number, :year, :user_id, :car_manufacturer_id, :car_model_id, :edited_by, :picture)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/car_models_helper.rb
module CarModelsHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<div class="navbar-wrapper">
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Intermobile" , root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="navbar-right">
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
     <% if user_signed_in? %>
       
        <li><%= link_to "My Cars", cars_path %></li>
    <%= render 'layouts/service_transaction' %>
         <li> <%= render 'notifications/notification_dropdown' %></li>
          <% if current_user.role.name == 'admin' %>
          <li><%= link_to "Admin", rails_admin_path %></li>
          <% end %>
        <% end %> 
              <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
                   <ul class="dropdown-menu">
                         <% if user_signed_in? %>
                            <li> <%= link_to "Logged In As #{current_user.role.name} : "+current_user.email, "#" , class: "not-active" %></li>
                              <li> <%= link_to "Edit Account Info ", edit_user_registration_path %></li>
                            <li><%= link_to "Log out",  destroy_user_session_path, method: "delete" %></li>
                             <li><%= link_to "New: try our android app",  "https://www.dropbox.com/s/cogotkxuzgxp5nk/Intrmbl.apk?dl=0" %></li>


                          <% else %>
                          <li><%= link_to "Sign Up", new_user_registration_path %></li>
                            <li><%= link_to "Log In", new_user_session_path %></li>
                          
                          <li><%= link_to "New: try our android app",  "https://www.dropbox.com/s/cogotkxuzgxp5nk/Intrmbl.apk?dl=0" %>

                          <% end %>
                      </ul>

                  </li>
                  
          
        </ul>
     
 
  
    
        
               
  
 
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</div>

app/views/layouts/_service_transaction.html.erb
  <li class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Transaction <span class="caret"></span></a>
                   <ul class="dropdown-menu">
                         <% if user_signed_in? %>
                            <% if current_user.role.name == "admin" || current_user.role.name == "staff" %>
                            <li> <%= link_to "New Service Transaction", new_service_transaction_path  %></li>
                            <% else %>
                            <% end %>
                            <li><%= link_to "View Service Transactions", service_transactions_path  %></li>
                            <% end %>
                              <li><%= link_to "View Service Offered", services_path  %></li>
                      </ul>
                  </li>
                  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intermobile</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<p class="notice"><%= notice %></p>
	       <p class="alert"><%= alert %></p>

<%= yield %>
</div>
</body>
</html>