config/routes.rb
Rails.application.routes.draw do
  

 
  get 'notifications/:id/link_through', to: 'notifications#link_through',
                                        as: :link_through
  get 'notifications', to: 'notifications#index' 
  resources :services
  resources :car_models
  resources :cars
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users

  resources :service_transactions do
    resources :comments
    resources :service_todos, only: [:index, :new, :create] do
      member do
          patch :completed
          patch :on_going
          patch :paid
      end
    end
  end
 resources :service_transactions do 
    member do
      patch :finished
    end
  end
 resources :service_todos, only: [:show, :edit, :update, :destroy]
   resources :service_transactions 

  get 'home/index'

  root 'home#index'

end

app/controllers/service_transactions_controller.rb
class ServiceTransactionsController < ApplicationController
  before_action :set_service_transaction, only: [:show, :edit, :update, :destroy, :finished]

  # GET /service_transactions
  # GET /service_transactions.json
  def index
    if current_user.role.name == "user"
      @service_transactions = current_user.service_transactions.paginate(:page => params[:page], :per_page => 20).order('created_at DESC')
    
    else
      
      @service_transactions = ServiceTransaction.all.paginate(:page => params[:page], :per_page => 40).order('created_at DESC')
    end
  end



  # GET /service_transactions/1
  # GET /service_transactions/1.json
  def show
    #disallow users to view what isnt theirs
     if current_user.id == @service_transaction.car.user_id

     elsif current_user.role.name == "admin" || current_user.role.name == "staff"|| current_user.role.name == "technician"
     else
        redirect_to root_path, notice: "You do not have permission to view this."
     end
      @comments = Comment.where(service_transaction_id: @service_transaction)
     @service_todos = ServiceTodo.where(service_transaction_id: @service_transaction)
  end

  # GET /service_transactions/new
  def new
    if current_user.role.name == "admin" || current_user.role.name == "staff"
      @service_transaction = ServiceTransaction.new
    else
      redirect_to service_transactions_path, notice: "You do not have permission to access page"
    end
    #@service_transaction.service_todos.build
  end

  # GET /service_transactions/1/edit
  def edit
    if current_user.role.name == "admin" || current_user.role.name == "staff"
    else
        redirect_to root_path, notice: "Dont have permission"
    end
  end

  # POST /service_transactions
  # POST /service_transactions.json
  def create
    
    @service_transaction = ServiceTransaction.new(service_transaction_params)

    respond_to do |format|
      if @service_transaction.save
          Notification.create(user_id: @service_transaction.car.user_id,
                          notified_by_id: current_user.id,
                          car_id: @service_transaction.car_id,
                          service_transaction_id: @service_transaction.id,
                          notice_type: 'created a new transaction for you')
         Notification.create(user_id: @service_transaction.technician_in_charge_id,
                          notified_by_id: current_user.id,
                          car_id: @service_transaction.car_id,
                          service_transaction_id: @service_transaction.id,
                          notice_type: 'created a new transaction for you')
          Notification.create(user_id: @service_transaction.staff_in_charge_id,
                          notified_by_id: current_user.id,
                          car_id: @service_transaction.car_id,
                          service_transaction_id: @service_transaction.id,
                          notice_type: 'created a new transaction for you')
        format.html { redirect_to @service_transaction, notice: 'Service transaction was successfully created.' }
        format.json { render :show, status: :created, location: @service_transaction }
      else
        format.html { render :new }
        format.json { render json: @service_transaction.errors, status: :unprocessable_entity }
      end
    end
  end
  def finished
    #mailer =?
    if current_user.role.name == "admin" || current_user.role.name == "staff"
       @service_transaction.update_attribute(:finished_at, Time.now)
      if current_user.id == @service_transaction.staff_in_charge_id || current_user.role.name == "admin"
         ServiceTransactionMailer.finished(@service_transaction).deliver_later
           Notification.create(user_id: @service_transaction.car.user_id,
                            notified_by_id: current_user.id,
                            car_id: @service_transaction.car_id,
                            service_transaction_id: @service_transaction.id,
                            notice_type: 'marked Transaction  as finished')
           redirect_to @service_transaction, notice: "Service Transaction Finished."
        else
          redirect_to @service_transaction, notice: "Action Denied. Only the Technician-In-Charge and Admins have permission to mark this as complete."
        end

    else
      redirect_to @service_transaction, notice: "Action Stopped, Only Admin and Staff can mark this as Finished."
    end
  end  
  # PATCH/PUT /service_transactions/1
  # PATCH/PUT /service_transactions/1.json
  def update
    if current_user.role.name == "admin" || current_user.role.name == "staff"
    else
        redirect_to root_path, notice: "Dont have permission"
    end
    respond_to do |format|
      if @service_transaction.update(service_transaction_params)
        format.html { redirect_to @service_transaction, notice: 'Service transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @service_transaction }
      else
        format.html { render :edit }
        format.json { render json: @service_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /service_transactions/1
  # DELETE /service_transactions/1.json
  def destroy
    if current_user.role.name == "admin" || current_user.role.name == "staff"
        @service_transaction.destroy
        respond_to do |format|
          format.html { redirect_to service_transactions_url, notice: 'Service transaction was successfully destroyed.' }
          format.json { head :no_content }
        end
    else
        redirect_to root_path, notice: "Dont have permission"
    end
  
  end
  def notify_user
       Notification.create(user_id: @service_transaction.car.user_id,
                          notified_by_id: current_user.id,
                          car_id: @service_transaction.car_id,
                          service_transaction_id: @service_transaction.id,
                          notice_type: 'comment')

  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service_transaction
      @service_transaction = ServiceTransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_transaction_params
      params.require(:service_transaction).permit(:started_at, :finished_at, :car_id, :comments, :staff_in_charge_id, :technician_in_charge_id , :service_todos,:service_todos_attributes => [:service_id, :service_name])
    end
end

app/helpers/service_transactions_helper.rb
module ServiceTransactionsHelper
end

app/views/service_transactions/_form.html.erb
<%= simple_form_for(@service_transaction) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
   <%= f.association :staff_in_charge, collection: User.staff, :label_method => :email, :value_method => :id %>
    <%= f.association :technician_in_charge, collection: User.technician, :label_method => :email, :value_method => :id %>
   <%= f.association :car, :label_method => :plate_number, :value_method => :id %>
  </div>
  

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/service_transactions/edit.html.erb
<h1>Editing Service Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @service_transaction %> |
<%= link_to 'Back', service_transactions_path %>

app/views/service_transactions/index.html.erb
<h1>On-Going Service Transactions</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Service Transaction ID# :</th>
      <th>Added on : </th>
      <th>Finished at : </th>
      <th>Car: </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_transactions.where(finished_at: nil).each do |service_transaction| %>
      <tr>
        <td><%= service_transaction.id %></td>
        <td><%= service_transaction.created_at.strftime("%b-%d-%y, %I:%M %P")%>


        </td>
        <td><% if service_transaction.finished_at.nil? %>
          <font style="color: #4b95bf" > On-Going</font>
          <% else %>
          <%=  service_transaction.finished_at.strftime("%b-%d-%y, %I:%M %P") %>
          <% end %>
        </td>
        <td><%= link_to 'Show', service_transaction %></td>
        <% if current_user.role.name == "admin" || current_user.role.name="staff" %>
          <td><%= service_transaction.car.try(:plate_number) %></td>
          
          <td><%= link_to 'Edit', edit_service_transaction_path(service_transaction) %></td>
          <td><%= link_to 'Destroy', service_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service transaction', new_service_transaction_path %>
<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>



<h1>Past Service Transactions</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Service Transaction ID# :</th>
      <th>Added on : </th>
      <th>Finished at : </th>
      <th>Cars</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @service_transactions.where.not(finished_at: nil).each do |service_transaction| %>
      <tr>
        <td><%= service_transaction.id %></td>
        <td><%= service_transaction.created_at.strftime("%b-%d-%y, %I:%M %P")%>


        </td>
        <td><% if service_transaction.finished_at.nil? %>
          <font style="color: #4b95bf" > On-Going</font>
          <% else %>
          <%=  service_transaction.finished_at.strftime("%b-%d-%y, %I:%M %P") %>
          <% end %>
        </td>
        <td><%= link_to 'Show', service_transaction %></td>
        <% if current_user.role.name == "admin" || current_user.role.name="staff" %>
        <td><%= service_transaction.car.try(:plate_number) %></td>
        
        <td><%= link_to 'Edit', edit_service_transaction_path(service_transaction) %></td>
        <td><%= link_to 'Destroy', service_transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Service transaction', new_service_transaction_path %>
<%= will_paginate @collection, renderer: BootstrapPagination::Rails %>

app/views/service_transactions/new.html.erb
<h1>New Service Transaction</h1>

<%= render 'form' %>
<br>
<%= link_to 'Back', service_transactions_path, class: "btn btn-default" %>

app/views/service_transactions/show.html.erb
	 <% if current_user.role.name == "admin" || current_user.role.name == "staff" %>
		<p>	
				<% if @service_transaction.finished? %>
						<%= link_to "Marked as Finished", finished_service_transaction_path(@service_transaction), method: :patch, data: {confirm: "Are you sure you want to mark service as finished?"}, class: "btn btn-success disabled" %>
				<% else %>
					<%= link_to "Mark as Finished", finished_service_transaction_path(@service_transaction,), method: :patch, data: {confirm: "Are you sure you want to mark service as finished?"}, class: "btn btn-success" %>
				<% end %>
		</p>
	<% end %>
	
<div class="panel">
	<div class="panel panel-info">
		<div class="panel panel-heading">
		<p style="float: right">	
				<% if @service_transaction.finished? %>
						 <b>Status: </b><span class="label label-success">Transaction Completed</span>
				<% else %>
					 <b>Status: </b><span class="label label-default">Transaction On-Going</span>
				<% end %>
		</p>
		<% total_price = 0 %>
		<% if @service_todos.empty? %>

		<% else %>
			<% @service_todos.each do |service_todo| %>
			 <tr>
			 
			 	<% total_price += service_todo.service.try(:price) %>
				
			<% end %>
			<li //style="float: //right; //padding-right: //3rem;"> <strong>Service Transaction Summary: <%= number_to_currency(total_price, unit: "Php", separator: ".", delimiter: ",") %></strong></li>
				<% end %>
		<li>
	
		  <strong>Started at:</strong>
		  <%= (@service_transaction.created_at).strftime("%B %d,  %I : %M %P") %>
		</li>

		<li>
		  <strong>Finished at:</strong>
		  		  <%= @service_transaction.try(:finished_at).try(:strftime,"%B %d,  %I : %M %P") %>
		</li>

		<li>
		  <strong>Staff In Charge : </strong>
		  <%= @service_transaction.staff_in_charge.try(:email) %>
		</li>
		<li>
		  <strong>Technician In Charge : </strong>
		  <%= @service_transaction.technician_in_charge.try(:email) %>
		</li>
		<li>
		  <strong>Car :</strong>
		  <%= @service_transaction.car.try(:plate_number) %>
		</li>
		<li>
		  <strong>Car Owner:</strong>
		  <%= @service_transaction.car.user.try(:email) %>
		</li>
		<li>
		  <strong>Owner Contact Number:</strong>
		  <%= @service_transaction.car.user.try(:contact_number_prefix) %>-<%= @service_transaction.car.user.try(:contact_number) %>
		</li>
		</div>


	<div class="panel-body">
		<%= render @service_transaction.service_todos %>
			<!-- total price of all the service_todos -->
		
		<% if current_user.role.name == "admin" || current_user.role.name == "staff" %>
		<%= render 'service_todos/form' %>
		<% end %>
	</div>


		<div class="panel-footer">
		<h3>Comments:</h3>
		<% @comments.each do |comment| %>
			<strong><%= comment.user.email %> : </strong>
			<li class="comment">
			<%= comment.content %>
			</li>
		<% end %>
		<%= render 'comments/form' %>
		</div>
	</div>
<%= link_to 'Edit', edit_service_transaction_path(@service_transaction), class: "btn btn-default" %> |
<%= link_to 'Back', service_transactions_path, class: "btn btn-default" %>